"""add_external_courses_and_overrides

Revision ID: 14dc7cf10a5e
Revises: d28708650956
Create Date: 2026-05-24 08:28:38.383730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dc7cf10a5e'
down_revision: Union[str, None] = 'd28708650956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('study_mode', sa.String(length=50), server_default='standard', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'milestone_id', name='uq_user_milestone_override')
    )
    op.add_column('courses', sa.Column('is_external', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_external')
    op.drop_table('milestone_overrides')
    # ### end Alembic commands ###