"""add_subscription_details

Revision ID: 5c23d7513cf1
Revises: 9e4ce295609c
Create Date: 2026-05-23 20:45:25.641168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c23d7513cf1'
down_revision: Union[str, None] = '9e4ce295609c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_subscription_tier', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('polar_subscription_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'polar_subscription_id')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'pending_subscription_tier')
    # ### end Alembic commands ###